server:
  port: 4396
#配置文件git地址
spring:
  application:
    name: sequeneRise-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SequeneRise/config.git
          username: SequeneRise
          password: cc1598829
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10301/eureka/

